# Generated by Django 3.0.6 on 2021-08-11 17:46

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
